### ISSUE TITLE
How to use your package?

### ISSUE THREAD

**Issue by Juddd** [sw1sh/WolframClass#1]
Does this library enable mma to have OOP features? Can you provide instructions for use?

**Comment by sw1sh** [comment]
@Juddd Sorry for super late reply, somehow I've missed the notification about your comment.
This paclet is in the repository with some examples: https://resources.wolframcloud.com/PacletRepository/resources/Wolfram/Class. It was an experiment as I was also trying to learn about tinygrad abstractions while porting them to WL: https://github.com/sw1sh/TinyGrad
